---
title: "Full PRS Script"
author: "Nick Sumpter"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
      rmarkdown::render(inputFile,
                        encoding = encoding, 
                        output_file = here::here("Output/HTMLs", "PRS.html")) })
output:
  html_document:
    code_folding: hide
    toc: TRUE
---

```{r setup, warning = FALSE, message = FALSE}
# Libraries
library(here)
library(vroom)
library(knitr)
library(kableExtra)
library(lubridate)
library(viridis)
library(janitor)
library(sciplot)
library(meta)
library(broom)
library(MASS)
library(ez)
library(car)
library(pastecs)
library(qqman)
library(ggrepel)
library(fs)
library(tidyverse)

knitr::opts_chunk$set(fig.width = 8.5)

# Set theme for ggplot
theme_set(theme_bw())
```

```{r GWAS, child = here::here("Script/Rmds", "PRS_GWAS.Rmd")}

```

<br/>

```{r Data Preparation, child = here::here("Script/Rmds", "PRS_Dataprep.Rmd")}

```

<br/>

```{r Data Exploration, child = here::here("Script/Rmds", "PRS_DataExploration.Rmd")}

```

<br/>

```{r Models, child = here::here("Script/Rmds", "PRS_Models.Rmd")}

```

<br/>

```{r Plots, child = here::here("Script/Rmds", "PRS_Plots.Rmd")}

```
